#ifndef MyConstants_CONST
#define MyConstants_CONST

// Global literal constants used in code

// Descriptive literal constants used for better readibility of code
#define MS_IN_ONE_SECOND 1000ULL
#define SECONDS_IN_ONE_MINUTE 60
#define MINUTES_IN_ONE_HOUR 60
#define HOURS_IN_ONE_DAY 24
#define FIVE_MINUTES 5
#define LED_GROUPS_COUNT 6
#define LED_INDIVIDUALS_COUNT 3
#define LEDS_TOTAL LED_GROUPS_COUNT *LED_INDIVIDUALS_COUNT
#define CLOCK_LEDS_COUNT 12
#define SOCKETS_COUNT 5
#define SOCKET_LEDS_COUNT SOCKETS_COUNT
#define BITS_IN_ONE_BYTE 8
#define MS_IN_ONE_MINUTE MS_IN_ONE_SECOND *SECONDS_IN_ONE_MINUTE
#define MS_IN_ONE_HOUR MS_IN_ONE_MINUTE *MINUTES_IN_ONE_HOUR
#define EEPROM_SOCKET_ACTIVITY_BYTES_TOTAL HOURS_IN_ONE_DAY *MINUTES_IN_ONE_HOUR / FIVE_MINUTES *SOCKETS_COUNT / BITS_IN_ONE_BYTE // (24*60/5*5/8)=180
#define EEPROM_SOCKET_ACTIVITY_END_BYTE_ADDRES EEPROM_SOCKET_ACTIVITY_START_BYTE_ADDRES + EEPROM_SOCKET_ACTIVITY_BYTES_TOTAL - 1

#endif