#ifndef MyConstants_CONST
#define MyConstants_CONST

// Global literal constants used in code

// Descriptive literal constants used for better readibility of code
#define MS_IN_ONE_SECOND 1000UL
#define SECONDS_IN_ONE_MINUTE 60UL
#define MINUTES_IN_ONE_HOUR 60UL
#define HOURS_IN_ONE_DAY 24UL
#define FIVE_MINUTES 5UL
#define LED_GROUPS_COUNT 6u
#define LED_INDIVIDUALS_COUNT 3u
#define LEDS_TOTAL (LED_GROUPS_COUNT * LED_INDIVIDUALS_COUNT)
#define CLOCK_LEDS_COUNT 12u
#define SOCKETS_COUNT 5u
#define SOCKET_LEDS_COUNT SOCKETS_COUNT
#define BITS_IN_ONE_BYTE 8u
#define MS_IN_ONE_MINUTE (MS_IN_ONE_SECOND * SECONDS_IN_ONE_MINUTE)
#define MS_IN_ONE_HOUR (MS_IN_ONE_MINUTE * MINUTES_IN_ONE_HOUR)
#define MS_IN_ONE_DAY (MS_IN_ONE_HOUR * HOURS_IN_ONE_DAY)
#define EEPROM_SOCKET_ACTIVITY_BYTES_TOTAL (HOURS_IN_ONE_DAY * MINUTES_IN_ONE_HOUR / FIVE_MINUTES * SOCKETS_COUNT / BITS_IN_ONE_BYTE) // (24*60/5*5/8)=180
#define EEPROM_SOCKET_ACTIVITY_END_BYTE_ADDRES (EEPROM_SOCKET_ACTIVITY_START_BYTE_ADDRES + EEPROM_SOCKET_ACTIVITY_BYTES_TOTAL - 1u)

#endif