#ifndef MyValidation_VALIDATOR
#define MyValidation_VALIDATOR

#include "UserSettings.const.h"

//MEMORY CONFIGURATION in UserSettings
#if EEPROM_HOUR_BYTE_ADDRES >= EEPROM_SOCKET_ACTIVITY_START_BYTE_ADDRES && EEPROM_HOUR_BYTE_ADDRES < EEPROM_SOCKET_ACTIVITY_END_BYTE_ADDRES ||     \
    EEPROM_MINUTE_BYTE_ADDRES >= EEPROM_SOCKET_ACTIVITY_START_BYTE_ADDRES && EEPROM_MINUTE_BYTE_ADDRES < EEPROM_SOCKET_ACTIVITY_END_BYTE_ADDRES || \
    EEPROM_SECOND_BYTE_ADDRES >= EEPROM_SOCKET_ACTIVITY_START_BYTE_ADDRES && EEPROM_SECOND_BYTE_ADDRES < EEPROM_SOCKET_ACTIVITY_END_BYTE_ADDRES || \
    EEPROM_LOGIC_LEVELS_BYTE_ADDRES >= EEPROM_SOCKET_ACTIVITY_START_BYTE_ADDRES && EEPROM_LOGIC_LEVELS_BYTE_ADDRES < EEPROM_SOCKET_ACTIVITY_END_BYTE_ADDRES
#error Not a valid memory configuration in UserSettings
#endif

#endif